# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: resourcehub

container: quay.io/redhat-appstudio/rhtap-task-runner:latest

variables:
- group: acmiel-variables

steps:
- script: cosign version
  displayName: Check if we have cosign

- script: |
    #!/bin/bash
    set -xeuo pipefail

    echo -n "${COSIGN_PUBLIC_KEY}" | wc -c
    echo -n "${COSIGN_SECRET_KEY}" | wc -c
    echo -n "${TRUSTIFICATION_OIDC_CLIENT_SECRET}" | wc -c
  env:
    # normal variables are set automatically, but secrets have to be set explicitly :(
    COSIGN_SECRET_KEY: $(COSIGN_SECRET_KEY)
    TRUSTIFICATION_OIDC_CLIENT_SECRET: $(TRUSTIFICATION_OIDC_CLIENT_SECRET)
